// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (C) 2026 <developer@mplx.eu>

// Code generated by scripts/gen-version.sh from git state; DO NOT EDIT.

package version

func init() { Version = "0.14.0-dev+8.ce22fcc" }
