#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <jennifer@mplx.dev>
#
# Regenerate modules/pdfwriter_afm.j - the standard-14 font advance-width tables
# pdfwriter uses for text-layout width measurement. The widths are the Adobe
# Core 14 AFM metrics, indexed by WinAnsi code (0-255) to match the
# /WinAnsiEncoding pdfwriter emits for the standard-14 fonts.
#
# The Core 14 metrics are frozen, so this is provenance / reproducibility rather
# than a build step; run it only to re-derive the committed file. It needs
# reportlab (a dev-only dependency, not used by the interpreter):
#
#     pip install --user reportlab
#     python3 scripts/gen-pdfwriter-afm.py
#
# Helvetica-Oblique shares Helvetica's widths and Helvetica-BoldOblique shares
# Helvetica-Bold's; the Times faces are all distinct; the Courier faces are
# monospaced (constant 600, handled in pdfwriter.j without a table); Symbol /
# ZapfDingbats are symbol fonts with no layout metrics.

import os
from reportlab.pdfbase import _fontdata

OUT = os.path.join(os.path.dirname(__file__), "..", "modules", "pdfwriter_afm.j")

# The distinct tables pdfwriter needs; afmWidths() aliases the oblique/bold
# faces onto these and special-cases Courier.
SPECS = [
    ("AFM_HELVETICA", "Helvetica"),
    ("AFM_HELVETICA_BOLD", "Helvetica-Bold"),
    ("AFM_TIMES", "Times-Roman"),
    ("AFM_TIMES_BOLD", "Times-Bold"),
    ("AFM_TIMES_ITALIC", "Times-Italic"),
    ("AFM_TIMES_BOLDITALIC", "Times-BoldItalic"),
]

HEADER = """\
# SPDX-License-Identifier: LGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <jennifer@mplx.dev>
#
# pdfwriter_afm.j - standard-14 font metrics for pdfwriter text layout, included
# (textual splice) into pdfwriter.j. Each table is a font's glyph advance widths
# in 1000-unit em space, indexed by WinAnsi code (0-255), derived from the Adobe
# Core 14 AFM data. Helvetica-Oblique shares Helvetica's widths and
# Helvetica-BoldOblique shares Helvetica-Bold's; the Times faces are all distinct;
# the Courier faces are monospaced (constant 600, handled without a table);
# Symbol / ZapfDingbats are symbol fonts and have no layout metrics. afmWidths(font)
# selects a table. Private to the module; it declares no `use` of its own.
#
# Generated by scripts/gen-pdfwriter-afm.py; do not edit by hand.
"""

LOOKUP = """\
# afmWidths returns the WinAnsi-code -> 1000-em advance table for a standard-14
# text font, or an empty list for Courier (monospaced) / symbol fonts.
func afmWidths(font as string) {
    if ($font == "Helvetica" or $font == "Helvetica-Oblique") { return AFM_HELVETICA; }
    if ($font == "Helvetica-Bold" or $font == "Helvetica-BoldOblique") { return AFM_HELVETICA_BOLD; }
    if ($font == "Times-Roman") { return AFM_TIMES; }
    if ($font == "Times-Bold") { return AFM_TIMES_BOLD; }
    if ($font == "Times-Italic") { return AFM_TIMES_ITALIC; }
    if ($font == "Times-BoldItalic") { return AFM_TIMES_BOLDITALIC; }
    return [];
}
"""


def table(font, enc, widths):
    glyphs = widths[font]
    out = []
    for code in range(256):
        name = enc[code] if code < len(enc) else None
        out.append(int(glyphs.get(name, 0)) if name and name != ".notdef" else 0)
    return out


def main():
    widths = _fontdata.widthsByFontGlyph
    enc = _fontdata.encodings["WinAnsiEncoding"]
    parts = [HEADER.rstrip("\n"), ""]
    for cname, font in SPECS:
        t = table(font, enc, widths)
        rows = ["    " + ", ".join(str(v) for v in t[i:i + 16]) for i in range(0, 256, 16)]
        parts.append("def const %s as list of int init [" % cname)
        parts.append(",\n".join(rows))
        parts.append("];")
        parts.append("")
    parts.append(LOOKUP)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
