#!/bin/sh
# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (C) 2026 mplx <jennifer@mplx.dev>
#
# Writes internal/version/version_gen.go with the current build version.
# Called by the Makefile before each build target. The generated file is
# .gitignored; `go test` without running this script falls back to the
# default "dev" baked into version.go.

set -eu

here=$(cd "$(dirname "$0")" && pwd)
ver=$(sh "$here/version.sh")
out="$here/../internal/version/version_gen.go"

cat > "$out" <<EOF
// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (C) 2026 mplx <jennifer@mplx.dev>

// Code generated by scripts/gen-version.sh from git state; DO NOT EDIT.

package version

func init() { Version = "$ver" }
EOF

echo "wrote $out (Version=$ver)"
