#!/usr/bin/env -S jennifer run
# SPDX-License-Identifier: LGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <jennifer@mplx.dev>

/**
 * Generate the per-module API reference under docs/api/ from each shipped
 * module's own doc comments, dogfooding the `docblock` module: docblock.parse
 * turns a module's source into structured docs, and this program renders them
 * to Markdown. It writes one page per module, the docs/api/index.md catalog,
 * and refreshes the marked "Module API Reference" region of docs/SUMMARY.md.
 * With --pdf it also renders the combined reference to a single PDF
 * (docs/api/jennifer-module-api.pdf) via markdown.toPdf - dogfooding it, and opt-in
 * because laying out the ~360-page document is much slower than the Markdown pass.
 *
 * Run from the repository root:
 *   jennifer run scripts/gen-module-docs.j            # Markdown only (fast)
 *   jennifer run scripts/gen-module-docs.j --pdf      # also the combined PDF
 *
 * The output is NOT committed (docs/api/ and the SUMMARY region are gitignored):
 * the docs workflow (.github/workflows/docs.yml) runs this generator before
 * every mdBook build, so the published API reference is always in step with the
 * code without any regenerate-and-commit dance. The PR test workflow runs it too,
 * as a smoke-check. The set of documented modules mirrors the module lint step:
 * every module source file that is not a *_test.j overlay and not an
 * include-partial (those are documented through the parent that splices them in).
 */

use io;
use fs;
use os;
use path;
use strings;
use lists;
use time;

import "../modules/docblock.j" as docblock;
import "../modules/markdown.j" as markdown;

def const MODDIR as string init "modules";
def const OUTDIR as string init "docs/api";
def const APIPDF as string init "docs/api/jennifer-module-api.pdf";
def const SUMMARY as string init "docs/SUMMARY.md";
def const START as string init "<!-- api:start - generated by scripts/gen-module-docs.j; " +
    "do not edit this region by hand -->";
def const END as string init "<!-- api:end -->";

# sort keys for deterministic output (the same input always renders identically).
func funcKey(f as docblock.FuncDoc) {
    return $f.name;
}
func structKey(s as docblock.StructDoc) {
    return $s.name;
}
func enumKey(e as docblock.EnumDoc) {
    return $e.name;
}
func constKey(c as docblock.ConstDoc) {
    return $c.name;
}

# includedPartials scans every module for `include "x.j"` and returns the
# basenames spliced into another module (documented via their parent, not alone).
# entryModules returns the sorted stems of the modules to document - every module
# source that is not a *_test.j overlay and not a *.inc.j include-partial (a partial
# is spliced into a parent, so it is documented through that parent).
func entryModules() {
    def stems as list of string;
    for (def name in fs.list(MODDIR)) {
        if (strings.endsWith($name, ".j") and not strings.endsWith($name, "_test.j") and
            not strings.endsWith($name, ".inc.j")) {
            $stems[] = path.stem($name);
        }
    }
    return lists.sort($stems);
}

# mdText escapes angle brackets so a literal placeholder like <token> in a
# description is not parsed as an HTML tag (mdBook warns on unclosed ones).
func mdText(s as string) {
    return strings.replace(strings.replace($s, "<", "&lt;"), ">", "&gt;");
}

# mdCell is mdText plus a pipe escape, for text inside a Markdown table cell.
func mdCell(s as string) {
    return strings.replace(mdText($s), "|", "\\|");
}

# exportedFuncs / -Structs / -Enums / -Consts keep only the public, non-internal
# members, sorted by name.
func exportedFuncs(all as list of docblock.FuncDoc) {
    def out as list of docblock.FuncDoc;
    for (def f in $all) {
        if ($f.exported and not $f.internal) {
            $out[] = $f;
        }
    }
    return lists.sortBy($out, funcKey);
}

func exportedStructs(all as list of docblock.StructDoc) {
    def out as list of docblock.StructDoc;
    for (def s in $all) {
        if ($s.exported and not $s.internal) {
            $out[] = $s;
        }
    }
    return lists.sortBy($out, structKey);
}

func exportedEnums(all as list of docblock.EnumDoc) {
    def out as list of docblock.EnumDoc;
    for (def e in $all) {
        if ($e.exported and not $e.internal) {
            $out[] = $e;
        }
    }
    return lists.sortBy($out, enumKey);
}

func exportedConsts(all as list of docblock.ConstDoc) {
    def out as list of docblock.ConstDoc;
    for (def c in $all) {
        if ($c.exported and not $c.internal) {
            $out[] = $c;
        }
    }
    return lists.sortBy($out, constKey);
}

# signature renders a call form: mod.name(p as type, ...).
func signature(mod as string, f as docblock.FuncDoc) {
    def parts as list of string;
    for (def p in $f.params) {
        $parts[] = $p.name + " as " + $p.type;
    }
    return $mod + "." + $f.name + "(" + strings.join($parts, ", ") + ")";
}

func renderFuncs(mod as string, funcs as list of docblock.FuncDoc) {
    def out as list of string;
    def fns as list of docblock.FuncDoc init exportedFuncs($funcs);
    if (len($fns) == 0) {
        return $out;
    }
    $out[] = "## Functions";
    $out[] = "";
    for (def f in $fns) {
        $out = lists.concat($out, renderOneFunc($mod, $f));
    }
    return $out;
}

# renderOneFunc renders a single function entry (its own helper keeps renderFuncs
# shallow rather than nesting the whole body under the for-each).
func renderOneFunc(mod as string, f as docblock.FuncDoc) {
    def out as list of string;
    $out[] = "### `" + signature($mod, $f) + "`";
    $out[] = "";
    if ($f.deprecated != "") {
        $out[] = "**Deprecated:** " + mdText($f.deprecated);
        $out[] = "";
    }
    if ($f.summary != "") {
        $out[] = mdText($f.summary);
        $out[] = "";
    }
    if ($f.description != "") {
        $out[] = mdText($f.description);
        $out[] = "";
    }
    if (len($f.params) > 0) {
        $out[] = "**Parameters**";
        $out[] = "";
        for (def p in $f.params) {
            $out[] = paramLine($p);
        }
        $out[] = "";
    }
    if ($f.returns.type != "") {
        def r as string init '**Returns** `{' + $f.returns.type + '}`';
        if ($f.returns.description != "") {
            $r = $r + " - " + mdText($f.returns.description);
        }
        $out[] = $r;
        $out[] = "";
    }
    if (len($f.throws) > 0) {
        $out[] = "**Throws**";
        $out[] = "";
        for (def t in $f.throws) {
            $out[] = throwLine($t);
        }
        $out[] = "";
    }
    for (def ex in $f.examples) {
        $out[] = "```jennifer";
        $out[] = $ex;
        $out[] = "```";
        $out[] = "";
    }
    return $out;
}

# paramLine / throwLine render one bullet, keeping the description escape out of
# the nested loops above.
func paramLine(p as docblock.ParamDoc) {
    def line as string init "- `" + $p.name + '` `{' + $p.type + '}`';
    if ($p.description != "") {
        $line = $line + " - " + mdText($p.description);
    }
    return $line;
}

func throwLine(t as docblock.ThrowDoc) {
    def line as string init '- `{' + $t.type + '}`';
    if ($t.description != "") {
        $line = $line + " - " + mdText($t.description);
    }
    return $line;
}

func renderStructs(mod as string, structs as list of docblock.StructDoc) {
    def out as list of string;
    def sts as list of docblock.StructDoc init exportedStructs($structs);
    if (len($sts) == 0) {
        return $out;
    }
    $out[] = "## Structs";
    $out[] = "";
    for (def s in $sts) {
        $out[] = "### `" + $mod + "." + $s.name + "`";
        $out[] = "";
        if ($s.summary != "") {
            $out[] = mdText($s.summary);
            $out[] = "";
        }
        if (len($s.fields) > 0) {
            $out[] = "| Field | Type | Description |";
            $out[] = "| ----- | ---- | ----------- |";
            for (def fld in $s.fields) {
                $out[] = "| `" + $fld.name + "` | `" + $fld.type + "` | " +
                    mdCell($fld.description) + " |";
            }
            $out[] = "";
        }
    }
    return $out;
}

func renderEnums(mod as string, enums as list of docblock.EnumDoc) {
    def out as list of string;
    def ens as list of docblock.EnumDoc init exportedEnums($enums);
    if (len($ens) == 0) {
        return $out;
    }
    $out[] = "## Enums";
    $out[] = "";
    for (def e in $ens) {
        $out[] = "### `" + $mod + "." + $e.name + "`";
        $out[] = "";
        if ($e.summary != "") {
            $out[] = mdText($e.summary);
            $out[] = "";
        }
        if ($e.description != "") {
            $out[] = mdText($e.description);
            $out[] = "";
        }
    }
    return $out;
}

func renderConsts(mod as string, consts as list of docblock.ConstDoc) {
    def out as list of string;
    def cs as list of docblock.ConstDoc init exportedConsts($consts);
    if (len($cs) == 0) {
        return $out;
    }
    $out[] = "## Constants";
    $out[] = "";
    $out[] = "| Constant | Type | Description |";
    $out[] = "| -------- | ---- | ----------- |";
    for (def c in $cs) {
        $out[] = "| `" + $mod + "." + $c.name + "` | `" + $c.type + "` | " + mdCell($c.summary) +
            " |";
    }
    $out[] = "";
    return $out;
}

# renderModule builds the whole Markdown page for one module.
func renderModule(mod as string, doc as docblock.FileDoc) {
    def out as list of string;
    $out[] = "<!-- Generated by scripts/gen-module-docs.j from modules/" + $mod +
        ".j - do not edit. -->";
    $out[] = "";
    $out[] = "# `" + $mod + "` API reference";
    $out[] = "";
    if ($doc.module.summary != "") {
        $out[] = mdText($doc.module.summary);
        $out[] = "";
    }
    if ($doc.module.description != "") {
        $out[] = mdText($doc.module.description);
        $out[] = "";
    }
    def imp as string init "Import with `import \"" + $mod + ".j\" as " + $mod + ";`.";
    if (fs.exists("docs/modules/" + $mod + ".md")) {
        $imp = $imp + " See the [`" + $mod + "` guide](../modules/" + $mod +
            ".md) for prose and examples.";
    }
    $out[] = $imp;
    $out[] = "";
    $out = lists.concat($out, renderFuncs($mod, $doc.funcs));
    $out = lists.concat($out, renderStructs($mod, $doc.structs));
    $out = lists.concat($out, renderEnums($mod, $doc.enums));
    $out = lists.concat($out, renderConsts($mod, $doc.consts));
    return strings.join($out, "\n") + "\n";
}

# renderIndex builds docs/api/index.md: a catalog table of every module page.
func renderIndex(stems as list of string, summaries as map of string to string, hasPdf as bool) {
    def out as list of string;
    $out[] = "<!-- Generated by scripts/gen-module-docs.j - do not edit. -->";
    $out[] = "";
    $out[] = "# Module API reference";
    $out[] = "";
    $out[] = "One page per shipped module, generated from the module's own doc";
    $out[] = "comments. This is the exact, always-current public surface (every";
    $out[] = "exported function, struct, enum, and constant). For prose, rationale, and";
    $out[] = "runnable examples, see the [module guides](../modules/index.md).";
    $out[] = "";
    # Link the single-file PDF only when it was generated in this run, so the link
    # never dangles.
    if ($hasPdf) {
        $out[] = "The whole reference as a single PDF: [`jennifer-module-api.pdf`](jennifer-module-api.pdf).";
        $out[] = "";
    }
    $out[] = "| Module | Summary |";
    $out[] = "| ------ | ------- |";
    for (def s in $stems) {
        $out[] = "| [`" + $s + "`](" + $s + ".md) | " + mdCell($summaries[$s]) + " |";
    }
    $out[] = "";
    return strings.join($out, "\n");
}

# updateSummary rewrites the marked region of docs/SUMMARY.md with the API
# section (a part header plus one entry per module page).
func updateSummary(stems as list of string) {
    def src as string init fs.readString(SUMMARY);
    def a as int init strings.indexOf($src, START);
    def b as int init strings.indexOf($src, END);
    if ($a < 0 or $b < 0) {
        throw Error{
            kind: "gen",
            message: "SUMMARY.md is missing the api:start / api:end markers",
            file: SUMMARY,
            line: 0,
            col: 0
        };
    }
    def block as list of string;
    $block[] = START;
    $block[] = "";
    $block[] = "# Module API Reference";
    $block[] = "";
    $block[] = "- [Overview](api/index.md)";
    for (def s in $stems) {
        $block[] = "- [`" + $s + "`](api/" + $s + ".md)";
    }
    $block[] = "";
    $block[] = END;
    def head as string init strings.substring($src, 0, $a);
    def tail as string init strings.substring($src, $b + len(END), len($src));
    fs.writeString(SUMMARY, $head + strings.join($block, "\n") + $tail);
}

# stripComments drops the generated `<!-- ... -->` banner lines so the combined PDF
# renders clean prose (markdown.toPdf has no notion of HTML comments).
func stripComments(md as string) {
    def out as list of string;
    for (def line in strings.split($md, "\n")) {
        if (not strings.startsWith(strings.trim($line), "<!--")) {
            $out[] = $line;
        }
    }
    return strings.join($out, "\n");
}

# --- driver ---

# generate refreshes the per-module Markdown pages, the index, and the SUMMARY
# region. With --pdf it also renders the whole reference to one PDF via
# markdown.toPdf (dogfooding it); that is opt-in because laying out the ~360-page
# document is far slower than the Markdown pass.
func generate(doPdf as bool) {
    def mdStart as time.Time init time.now();
    def mods as list of string init entryModules();
    fs.mkdirAll(OUTDIR);
    def summaries as map of string to string;
    # Accumulate the whole reference as one Markdown document for the PDF (only when
    # asked - the join / render is the expensive part).
    def pdfParts as list of string;
    if ($doPdf) {
        $pdfParts[] = "# Jennifer Module API Reference";
        $pdfParts[] = "";
        $pdfParts[] = "The public surface of every shipped module, generated from the modules' own doc comments by scripts/gen-module-docs.j.";
    }
    def count as int init 0;
    for (def stem in $mods) {
        def src as string init fs.readString(path.join(MODDIR, $stem + ".j"));
        def doc as docblock.FileDoc init docblock.parse($src);
        $summaries[$stem] = $doc.module.summary;
        def page as string init renderModule($stem, $doc);
        fs.writeString(path.join(OUTDIR, $stem + ".md"), $page);
        if ($doPdf) {
            $pdfParts[] = "";
            $pdfParts[] = stripComments($page);
        }
        $count = $count + 1;
    }
    fs.writeString(path.join(OUTDIR, "index.md"), renderIndex($mods, $summaries, $doPdf));
    updateSummary($mods);
    def mdMs as int init time.milliseconds(time.sub(time.now(), $mdStart));
    io.printf("generated %d module API pages into %s/ + index + SUMMARY region in %d ms\n", $count, OUTDIR, $mdMs);
    if ($doPdf) {
        def pdfStart as time.Time init time.now();
        # A dense reference: tighter margins than the markdown.toPdf default, shaded
        # heading bars (darker for higher levels), and a light table-header band.
        def opts as markdown.PdfOptions init markdown.pdfDefaults();
        $opts.margin = 45;
        $opts.tableHeaderFill = markdown.gray(232);
        $opts.headingStyles = [
            markdown.headingStyle(markdown.gray(205)),
            markdown.headingStyle(markdown.gray(222)),
            markdown.headingStyle(markdown.gray(236)),
            markdown.headingStyle(markdown.noFill()),
            markdown.headingStyle(markdown.noFill()),
            markdown.headingStyle(markdown.noFill())
        ];
        def pdfBytes as bytes init markdown.toPdfWith(strings.join($pdfParts, "\n"), $opts);
        fs.writeBytes(APIPDF, $pdfBytes);
        def pdfMs as int init time.milliseconds(time.sub(time.now(), $pdfStart));
        io.printf("rendered the combined reference to %s (%d bytes) in %d ms\n", APIPDF, len($pdfBytes), $pdfMs);
    }
}

# Pass --pdf to also render the combined PDF (slower); omit it for a fast Markdown-only run.
generate(os.hasFlag("--pdf"));
