#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (C) 2026 mplx <jennifer@mplx.dev>
#
# Regenerate theme/highlight.js = mdBook's bundled highlight.js + the Jennifer
# language definition (editors/highlightjs/jennifer.js), so the docs site
# highlights `.j` code blocks. mdBook highlights client-side with highlight.js
# and only supports adding a language by replacing the whole highlight.js
# bundle via a theme override; this script produces that override.
#
# Run it after bumping the pinned mdBook version (its bundled highlight.js may
# change) or after editing the Jennifer highlight definition. Verify the result
# in a browser (mdBook highlights at page load, so the static HTML has no
# highlight spans - open a page or headless-render it).

set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v mdbook >/dev/null 2>&1; then
  echo "gen-docs-highlight: mdbook not found on PATH" >&2
  exit 1
fi

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# Extract mdBook's stock highlight.js by building once WITHOUT our override.
[ -f theme/highlight.js ] && mv theme/highlight.js "$tmp/override.bak"
if ! mdbook build -d "$tmp/out" >/dev/null 2>&1; then
  # Restore the previous override before failing.
  [ -f "$tmp/override.bak" ] && mv "$tmp/override.bak" theme/highlight.js
  echo "gen-docs-highlight: mdbook build failed" >&2
  exit 1
fi
stock="$(ls "$tmp"/out/highlight-*.js | head -1)"

{
  echo "/* SPDX-License-Identifier: BSD-3-Clause AND LGPL-3.0-only */"
  echo "/* GENERATED by scripts/gen-docs-highlight.sh - do not edit by hand. */"
  echo "/* highlight.js (mdBook's bundled build, BSD-3-Clause,"
  echo "   https://github.com/highlightjs/highlight.js) + the Jennifer language"
  echo "   (LGPL-3.0-only, from editors/highlightjs/jennifer.js). This file"
  echo "   overrides mdBook's built-in highlight.js so the docs highlight .j. */"
  cat "$stock"
  # A leading ';' guards against ASI joining the bundle's last statement to the
  # appended IIFE.
  printf '\n;\n'
  echo "/* ---- Jennifer language (from editors/highlightjs/jennifer.js) ---- */"
  cat editors/highlightjs/jennifer.js
} > theme/highlight.js

echo "wrote theme/highlight.js ($(wc -c < theme/highlight.js) bytes)"
