#!/bin/sh
# SPDX-License-Identifier: LGPL-3.0-only
# SPDX-FileCopyrightText: Copyright (C) 2026 mplx <jennifer@mplx.dev>
#
# Generate docs/technical/coverage.md: a statement-coverage report for the Go
# system libraries (via `go test -cover`) and the Jennifer-coded modules (via
# `jennifer test --coverage`), then fill the marked "coverage" region of
# docs/SUMMARY.md with a link to it.
#
# Run from the repository root:
#   scripts/gen-coverage-docs.sh
#
# The output (docs/technical/coverage.md and the SUMMARY region) is generated at
# docs-build time by docs.yml, is gitignored (not committed), and is excluded
# from the manual PDF - the same model as the module API reference. Set JENNIFER
# to a prebuilt interpreter (default ./jennifer) so the per-module coverage runs
# do not each recompile.
set -eu

OUT="docs/technical/coverage.md"
SUMMARY="docs/SUMMARY.md"
JEN="${JENNIFER:-./jennifer}"
CSTART="<!-- coverage:start - generated by scripts/gen-coverage-docs.sh; do not edit this region by hand -->"
CEND="<!-- coverage:end -->"

# --- system libraries: one row per internal/lib package ---
lib_rows=$(go test -cover ./internal/lib/... 2>/dev/null | awk '
  /coverage:/ {
    name=""; pct=""
    for (i = 1; i <= NF; i++) {
      if ($i ~ /internal\/lib\//) { name = $i; sub(/.*internal\/lib\//, "", name) }
      if ($i ~ /%$/)              { pct = $i }
    }
    if (name != "" && pct != "") printf "| `%s` | %s |\n", name, pct
  }' | sort)

# --- modules: run each *_test.j overlay and read its module file coverage line ---
mod_rows=""
for tst in modules/*_test.j; do
  mod=${tst%_test.j}
  mod=${mod##*/}
  row=$("$JEN" test --coverage "$tst" 2>/dev/null | awk -v m="/modules/${mod}.j" '
    $1 ~ m"$" { gsub(/[()]/, "", $3); printf "| `%s` | %s |", "'"$mod"'", $3 }')
  if [ -n "$row" ]; then
    mod_rows="${mod_rows}${row}
"
  fi
done
mod_rows=$(printf '%s' "$mod_rows" | sort)

# --- emit the report page ---
{
  echo "<!-- Generated by scripts/gen-coverage-docs.sh - do not edit. -->"
  echo
  echo "# Test coverage"
  echo
  echo "Statement coverage of the Go **system libraries** and the Jennifer-coded"
  echo "**modules**, regenerated on every docs build so it reflects the current"
  echo "\`main\`. Coverage is one signal, not a target: some low numbers are device"
  echo "I/O (\`spi\`, \`i2c\`, \`gpio\`, \`serial\`) that needs real hardware, or network"
  echo "clients exercised by integration tests that this per-package measure does"
  echo "not attribute here."
  echo
  echo "## System libraries (\`internal/lib/\`)"
  echo
  echo "| Library | Statement coverage |"
  echo "| ------- | ------------------ |"
  echo "$lib_rows"
  echo
  echo "## Modules (\`modules/\`)"
  echo
  echo "| Module | Statement coverage |"
  echo "| ------ | ------------------ |"
  echo "$mod_rows"
} > "$OUT"

# --- fill the SUMMARY coverage region (idempotent: replaces marker contents) ---
awk -v s="$CSTART" -v e="$CEND" '
  index($0, s) { print; print ""; print "- [Test coverage](technical/coverage.md)"; print ""; inregion = 1; next }
  index($0, e) { inregion = 0; print; next }
  !inregion    { print }
' "$SUMMARY" > "$SUMMARY.tmp" && mv "$SUMMARY.tmp" "$SUMMARY"

echo "gen-coverage-docs: wrote $OUT and filled the SUMMARY coverage region"
